### ISSUE TITLE
Throwing errors

### ISSUE THREAD

**Issue by jandrewmc** [jandrewmc/SoftwareEngineering#2]
I wonder if the errors we are throwing should not be c# errors  but our own errors.  as in rather than using c# for errors using our own method.

**Comment by mike-koch** [comment]
Would there be any benefit? The benefit of raising C# errors will allow the application to exit as expected. Otherwise we will need to create some sort of exception handling class that will call `Environment.Exit(exitCode)`. This won't be testable btw as the test runner crashes when encountering `Environment.Exit`.

**Comment by jandrewmc** [comment]
Good point.  It was just something that I thought of.
